# Generated by Django 4.0.2 on 2022-02-13 12:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_uploadmodel_upload_file_uploadmodel_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='files', unique=True),
            preserve_default=False,
        ),
    ]
