# Generated by Django 4.0.2 on 2022-02-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_uploadmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='slug',
        ),
    ]
