# Generated by Django 4.0.2 on 2022-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_uploadmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='slug',
            field=models.SlugField(default='uuid.uuid1'),
        ),
    ]
