# Generated by Django 4.0.2 on 2022-02-13 12:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_uploadmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='files', unique=True),
        ),
    ]
