# Generated by Django 3.2.6 on 2022-02-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_uploadmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='files',
            field=models.FileField(upload_to='', verbose_name='Fayl'),
        ),
    ]
