# Generated by Django 4.0.2 on 2022-02-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_uploadmodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='files',
            field=models.TextField(verbose_name='DataFrame'),
        ),
    ]
