# Generated by Django 4.0.2 on 2022-02-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_uploadmodel_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='table',
            field=models.TextField(default='', verbose_name='DataFrame'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='files',
            field=models.FileField(upload_to='', verbose_name='Fayl'),
        ),
    ]
