# Generated by Django 4.0.2 on 2022-02-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_uploadmodel_table_alter_uploadmodel_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='files',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='slug',
        ),
    ]
