# Generated by Django 4.0.2 on 2022-02-19 02:20

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_remove_uploadmodel_files_remove_uploadmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='name',
            field=models.TextField(default='', verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
